FROM golang:1.25rc2-bookworm AS build

RUN go install github.com/anyproto/any-sync-tools/any-sync-network@latest

RUN apt-get update && apt-get install -y --no-install-recommends curl yq ca-certificates
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

COPY . .
RUN uv sync --locked

ENTRYPOINT ["bash", "create_config.sh"]
